use_frameworks!

target 'ICASpecificationModelType_Example' do
  pod 'ICASpecificationModelType', :path => '../'

  target 'ICASpecificationModelType_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
