//
//  ICASpecificationENLocaliseString.swift
//  Pods
//
//  Created by Wahyu Sumartha on 06/09/2017.
//
//

import Foundation

struct ICASpecificationENLocaliseString: ICASpecificationLocaliseType {
  let cylinders: String = "Cylinder"
  let doors: String = "Doors"
  let bore: String = "Bore"
  let stroke: String = "Stroke"
  let compressionRatio: String = "Compression Ratio"
  let seatCapacity: String = "Seat Capacity"
  let peakPower: String = "Peak Power"
  let horsePower: String = "Horse Power"
  let peakTorque: String = "Peak Torque(hp)"
  let fuelConsumption: String = "Fuel Consumption (L/100 km)"
  let co2Emission: String = "CO2 Emission"
  let gearNumber: String = "Gear Number"
  let steeringTurn: String = "Steering Turn"
  let steeringRadius: String = "Steering Radius"
  let length: String = "Length (mm)"
  let width: String = "Width (mm)"
  let height: String = "Height (mm)"
  let wheelBase: String = "Wheel Base (mm)"
  let frontTread: String = "Front Tread"
  let rearTread: String = "Rear Tread"
  let frontOverhang: String = "Front Overhang"
  let rearOverhang: String = "Rear Overhang"
  let groundClearance: String = "Ground Clearance"
  let kerbWeight: String = "Kerb Weight (kg)"
  let boot: String = "Boot"
  let fuelTank: String = "Fuel Tank"
  let duration: String = "Duration 0-100 km/h"
  let topSpeed: String = "Top Speed"
  let dryWeight: String = "Dry Weight(kg)"
  let seatHeight: String = "Seat Height"
  let engineModel: String = "Engine Model"
  let powerRPMFrom: String = "Power RPM From"
  let torqueRPMFrom: String = "Torque RPM From"
  let torqueRPMTo: String = "Torque RPM To"
  let engineType: String = "Engine Type"
  let directInjection: String = "Direct Injection"
  let aspiration: String = "Aspiration"
  let gearBoxType: String = "Gear Box Type"
  let finalDriveRatio: String = "Final Drive Ratio"
  let drivenWheel: String = "Driven Wheel"
  let frontBrakes: String = "Front Brakes"
  let rearBrakes: String = "Rear Brakes"
  let frontSuspension: String = "Front Suspension"
  let rearSuspension: String = "Rear Suspension"
  let steeringType: String = "Steering Type"
  let frontTyre: String = "Front Tyre"
  let rearTyre: String = "Rear Tyre"
  let frontRim: String = "Front Rim"
  let rearRim: String = "Rear Rim"
  let assembled: String = "Assembled"
  let fuelType: String = "Fuel Type"
  let coolingType: String = "Cooling Type"
  let wheelsType: String = "Wheels Type"
}
